Fix build on OpenBSD: setsockopt(2) has no SO_NOSIGPIPE
```
.../zeek-8.0.1/zeek-8.0.1/auxil/broker/caf/libcaf_net/src/network_socket.cpp:72:48: error: use of undeclared identifier 'SO_NOSIGPIPE'
   72 |                   setsockopt(x.id, SOL_SOCKET, SO_NOSIGPIPE, &value,
      |                                                ^
```

This is the only tweak required for CAF to work on OpenBSD, at least
when built as part of Zeek.

ajacoutot@ wrote this patch in 2022 as the previous port maintainer.